# Generated by Django 3.0.5 on 2021-09-16 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='items',
            new_name='title',
        ),
    ]
